keys:
  - &puiyq age1p4hwz0g5w90u6taf2su2qvgweny5xdwzcus34d92udm2xxhy7evqu9ar7c
  - &popipa age1un04rf9699f952f0lgaddkhyaqdkxfsxrqmj3w769gjvz4jj4vfqrlu6q4
creation_rules:
  - path_regex: secrets/popipa\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *puiyq
          - *popipa
