keys:
  - &puiyq age1p4hwz0g5w90u6taf2su2qvgweny5xdwzcus34d92udm2xxhy7evqu9ar7c
  - &nixos age1un04rf9699f952f0lgaddkhyaqdkxfsxrqmj3w769gjvz4jj4vfqrlu6q4
# - &vps secret
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *puiyq
          - *nixos
        # - *vps
