{ host, ... }:
let
  inherit (import ../../../hosts/${host}/variables.nix)
    browser
    terminal
    ;
in
{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "SUPER,T,pass,match:class ^(com.mitchellh.ghostty)$"
      "SUPER,V,exec, vicinae vicinae://extensions/vicinae/clipboard/history"
      "SUPER,Return,exec,${terminal} +new-window"
      "SUPER_SHIFT,N,exec,swaync-client -rs"
      "SUPER_SHIFT,Return,exec,vicinae toggle"
      "SUPER,W,exec,${browser}"
      "SUPER,K,exec,vicinae vicinae://extensions/sovereign/hypr-keybinds/hyprland-keybinds"
      "SUPER ALT,W,exec,wallsetter"
      "SUPER,Y,exec,ghostty --title=Yazi -e yazi"
      "SUPER,S,exec,screenshootin"
      "SUPER,D,exec,discord"
      "SUPER,O,exec,obs"
      "SUPER,C,exec,hyprpicker -a"
      "SUPER,G,exec,gimp"
      "SUPER,M,exec,pavucontrol"
      "SUPER,Q,killactive,"
      "SUPER,P,pseudo,"
      "SUPER_SHIFT,I,togglesplit,"
      "SUPER,F,fullscreen,"
      "SUPER_SHIFT,F,togglefloating,"
      "SUPER ALT,F,workspaceopt, allfloat"
      "SUPER_SHIFT,C,exit,"
      "SUPER_SHIFT,left,movewindow,l"
      "SUPER_SHIFT,right,movewindow,r"
      "SUPER_SHIFT,up,movewindow,u"
      "SUPER_SHIFT,down,movewindow,d"
      "SUPER_SHIFT,h,movewindow,l"
      "SUPER_SHIFT,l,movewindow,r"
      "SUPER_SHIFT,k,movewindow,u"
      "SUPER_SHIFT,j,movewindow,d"
      "SUPER ALT, left, resizeactive,-20 0"
      "SUPER ALT, right, resizeactive,20 0"
      "SUPER ALT, up, resizeactive,0 -20"
      "SUPER ALT, down, resizeactive,0 20"
      "SUPER ALT, 43, swapwindow,l"
      "SUPER ALT, 46, swapwindow,r"
      "SUPER ALT, 45, swapwindow,u"
      "SUPER ALT, 44, swapwindow,d"
      "SUPER,left,movefocus,l"
      "SUPER,right,movefocus,r"
      "SUPER,up,movefocus,u"
      "SUPER,down,movefocus,d"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPER,1,workspace,1"
      "SUPER,2,workspace,2"
      "SUPER,3,workspace,3"
      "SUPER,4,workspace,4"
      "SUPER,5,workspace,5"
      "SUPER,6,workspace,6"
      "SUPER,7,workspace,7"
      "SUPER,8,workspace,8"
      "SUPER,9,workspace,9"
      "SUPER,0,workspace,10"
      "SUPER_SHIFT,SPACE,movetoworkspace,special"
      "SUPER,SPACE,togglespecialworkspace"
      "SUPER_SHIFT,1,movetoworkspace,1"
      "SUPER_SHIFT,2,movetoworkspace,2"
      "SUPER_SHIFT,3,movetoworkspace,3"
      "SUPER_SHIFT,4,movetoworkspace,4"
      "SUPER_SHIFT,5,movetoworkspace,5"
      "SUPER_SHIFT,6,movetoworkspace,6"
      "SUPER_SHIFT,7,movetoworkspace,7"
      "SUPER_SHIFT,8,movetoworkspace,8"
      "SUPER_SHIFT,9,movetoworkspace,9"
      "SUPER_SHIFT,0,movetoworkspace,10"
      "SUPER CONTROL,right,workspace,e+1"
      "SUPER CONTROL,left,workspace,e-1"
      "SUPER,mouse_down,workspace, e+1"
      "SUPER,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "SUPER, mouse:272, movewindow"
      "SUPER, mouse:273, resizewindow"
    ];
  };
}
