{
  wayland.windowManager.hyprland.settings = {
    windowrule = [
      "float on, match:class ^(com.savedra1.clipse)$"
      "size 70% 70%, match:class ^(com.savedra1.clipse)$"
      "tag +file-manager, match:class ^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$"
      "tag +terminal, match:class ^(com.mitchellh.ghostty|org.wezfurlong.wezterm|Alacritty|kitty)$"
      "tag +browser, match:class ^(Brave-browser(-beta|-dev|-unstable)?)$"
      "tag +browser, match:class ^([Ff]iredragon|org.mozilla.firefox|[Ff]irefox-esr)$"
      "tag +browser, match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$"
      "tag +browser, match:class ^([Tt]horium-browser|[Cc]achy-browser|[Zz]en)$"
      "tag +projects, match:class ^(codium|codium-url-handler|VSCodium)$"
      "tag +projects, match:class ^(VSCode|code-url-handler)$"
      "tag +im, match:class ^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$"
      "tag +im, match:class ^([Ff]erdium)$"
      "tag +im, match:class ^(ZapZap)$"
      "tag +im, match:class ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"
      "tag +im, match:class ^(teams-for-linux)$"
      "tag +games, match:class ^(gamescope)$"
      "tag +games, match:class ^(steam_app_\d+)$"
      "tag +gamestore, match:class ^([Ss]team)$"
      "tag +gamestore, match:title ^([Ll]utris)$"
      "tag +gamestore, match:class ^(com.heroicgameslauncher.hgl)$"
      "tag +settings, match:class ^(gnome-disks|wihotspot(-gui)?)$"
      "tag +settings, match:class ^([Rr]ofi)$"
      "tag +settings, match:class ^(file-roller|org.gnome.FileRoller)$"
      "tag +settings, match:class ^(nm-applet|nm-connection-editor|blueman-manager)$"
      "tag +settings, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
      "tag +settings, match:class ^(nwg-look|qt5ct|qt6ct|[Yy]ad)$"
      "tag +settings, match:class (xdg-desktop-portal-gtk)"
      "tag +settings, match:class (.blueman-manager-wrapped)"
      "tag +settings, match:class (nwg-displays)"
      "move 72% 7%, match:title ^(Picture-in-Picture)$"
      "move (monitor_w-window_w)/2 (monitor_h-window_h)/2, match:class ^([Ff]erdium)$"
      "float on, match:class ^([Ww]aypaper)$"
      "move (monitor_w-window_w)/2 (monitor_h-window_h)/2, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
      "move (monitor_w-window_w)/2 (monitor_h-window_h)/2, match:class ([Tt]hunar), match:title negative:(.*[Tt]hunar.*)"
      "move (monitor_w-window_w)/2 (monitor_h-window_h)/2, match:title ^(Authentication Required)$"
      "idle_inhibit fullscreen, match:class .*"
      "idle_inhibit fullscreen, match:title .*"
      "idle_inhibit fullscreen, match:fullscreen 1"
      "float on, match:tag settings*"
      "float on, match:class ^([Ff]erdium)$"
      "float on, match:title ^(Picture-in-Picture)$"
      "float on, match:class ^(mpv|com.github.rafostar.Clapper)$"
      "float on, match:title ^(Authentication Required)$"
      "float on, match:class (codium|codium-url-handler|VSCodium), match:title negative:(.*codium.*|.*VSCodium.*)"
      "float on, match:class ^(com.heroicgameslauncher.hgl)$, match:title negative:(Heroic Games Launcher)"
      "float on, match:class ^([Ss]team)$, match:title negative:^([Ss]team)$"
      "float on, match:class ([Tt]hunar), match:title negative:(.*[Tt]hunar.*)"
      "float on, match:initial_title (Add Folder to Workspace)"
      "float on, match:initial_title (Open Files)"
      "float on, match:initial_title (wants to save)"
      "size 70% 60%, match:initial_title (Open Files)"
      "size 70% 60%, match:initial_title (Add Folder to Workspace)"
      "size 70% 70%, match:tag settings*"
      "size 60% 70%, match:class ^([Ff]erdium)$"
      "opacity 1.0 1.0, match:tag browser*"
      "opacity 0.9 0.8, match:tag projects*"
      "opacity 0.94 0.86, match:tag im*"
      "opacity 0.9 0.8, match:tag file-manager*"
      "opacity 0.8 0.7, match:tag terminal*"
      "opacity 0.8 0.7, match:tag settings*"
      "opacity 0.8 0.7, match:class ^(gedit|org.gnome.TextEditor|mousepad)$"
      "opacity 0.9 0.8, match:class ^(seahorse)$ # gnome-keyring gui"
      "opacity 0.95 0.75, match:title ^(Picture-in-Picture)$"
      "pin on, match:title ^(Picture-in-Picture)$"
      "keep_aspect_ratio on, match:title ^(Picture-in-Picture)$"
      "no_blur on, match:tag games*"
      "fullscreen on, match:tag games*"
    ];
  };
}
