"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
${custom.jj_name}\
${custom.jj_id}\
$git_status\
[](fg:yellow bg:green)\
$buf\
$bun\
$c\
$cpp\
$cmake\
$cobol\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$maven\
$meson\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$package\
$perl\
$php\
$pixi\
$purescript\
$python\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$solidity\
$spack\
$swift\
$terraform\
$typst\
$vlang\
$xmake\
$zig\
[](fg:green bg:sapphire)\
$aws\
$azure\
$conda\
$container\
$direnv\
$docker_context\
$gcloud\
$guix_shell\
$kubernetes\
$nats\
$netns\
$nix_shell\
$openstack\
$pulumi\
$singularity\
$vagrant\
[](fg:sapphire bg:lavender)\
$battery\
$memory_usage\
$shlvl\
$status\
$sudo\
$time\
$cmd_duration\
[ ](fg:lavender)\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "󰣇 "
Artix = "󰣇 "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = "󰣚 "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = "󰣛 "
FreeBSD = " "
Garuda = " "
Gentoo = "󰣨 "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = "󰌽 "
Mabox = " "
Macos = "󰀵 "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = "󰐿 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = "󰕈 "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = " "
Zorin = " "

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[hostname]
ssh_symbol = " "
style = "fg:crust bg:red"

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Desktop" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "
"Public" = "󰞉 "
"Templates" = " "
"Videos" = " "

[custom.jj_id]
symbol = "󱗆 "
style = "fg:crust bg:yellow"
format = '[ $symbol$output ]($style)'
when = "jj workspace root --ignore-working-copy"
command = "jj log --no-graph --no-pager --ignore-working-copy -r @ -T 'change_id.short()'"

[git_status]
disabled = false
style = "fg:crust bg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[buf]
symbol = " "
style = "fg:crust bg:green"

[bun]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[c]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[cpp]
symbol = " "
style = "fg:crust bg:green"

[cmake]
symbol = " "
style = "fg:crust bg:green"

[cobol]
symbol = " "
style = "fg:crust bg:green"

[crystal]
symbol = " "
style = "fg:crust bg:green"

[dart]
symbol = " "
style = "fg:crust bg:green"

[deno]
symbol = " "
style = "fg:crust bg:green"

[dotnet]
symbol = " "
style = "fg:crust bg:green"

[elixir]
symbol = " "
style = "fg:crust bg:green"

[elm]
symbol = " "
style = "fg:crust bg:green"

[erlang]
symbol = " "
style = "fg:crust bg:green"

[fennel]
symbol = " "
style = "fg:crust bg:green"

[fortran]
symbol = " "
style = "fg:crust bg:green"

[gleam]
symbol = " "
style = "fg:crust bg:green"

[golang]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[gradle]
symbol = " "
style = "fg:crust bg:green"

[haskell]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[haxe]
symbol = " "
style = "fg:crust bg:green"

[helm]
symbol = " "
style = "fg:crust bg:green"

[java]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[julia]
symbol = " "
style = "fg:crust bg:green"

[kotlin]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[lua]
symbol = " "
style = "fg:crust bg:green"

[maven]
symbol = " "
style = "fg:crust bg:green"

[meson]
symbol = "󰔷 "
style = "fg:crust bg:green"

[mojo]
symbol = "󰈸 "
style = "fg:crust bg:green"

[nim]
symbol = " "
style = "fg:crust bg:green"

[nodejs]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[ocaml]
symbol = " "
style = "fg:crust bg:green"

[odin]
symbol = "󰟢 "
style = "fg:crust bg:green"

[opa]
symbol = " "
style = "fg:crust bg:green"

[package]
symbol = "󰏗 "
style = "fg:crust bg:green"
format = '[ $symbol$version ]($style)'

[perl]
symbol = " "
style = "fg:crust bg:green"

[php]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[pixi]
symbol = "󰏗 "
style = "fg:crust bg:green"

[purescript]
symbol = " "
style = "fg:crust bg:green"

[python]
symbol = " "
style = "fg:crust bg:green"
format = '[ $symbol($version )(\(#$virtualenv\) )]($style)'

[raku]
symbol = "󱖊 "
style = "fg:crust bg:green"

[red]
symbol = "󱍼 "
style = "fg:crust bg:green"

[rlang]
symbol = "󰟔 "
style = "fg:crust bg:green"

[ruby]
symbol = " "
style = "fg:crust bg:green"

[rust]
symbol = "󱘗 "
style = "fg:crust bg:green"
format = '[ $symbol($version )]($style)'

[scala]
symbol = " "
style = "fg:crust bg:green"

[solidity]
symbol = " "
style = "fg:crust bg:green"

[spack]
symbol = " "
style = "fg:crust bg:green"

[swift]
symbol = " "
style = "fg:crust bg:green"

[terraform]
symbol = " "
style = "fg:crust bg:green"

[typst]
symbol = " "
style = "fg:crust bg:green"

[vlang]
symbol = " "
style = "fg:crust bg:green"

[xmake]
symbol = " "
style = "fg:crust bg:green"

[zig]
symbol = " "
style = "fg:crust bg:green"

[aws]
symbol = " "
style = "fg:crust bg:sapphire"

[azure]
symbol = " "
style = "fg:crust bg:sapphire"

[conda]
symbol = " "
style = "fg:crust bg:sapphire"
format = '[ $symbol$environment ]($style)'
ignore_base = false

[container]
symbol = " "
style = "fg:crust bg:sapphire"

[direnv]
symbol = " "
style = "fg:crust bg:sapphire"

[docker_context]
symbol = " "
style = "fg:crust bg:sapphire"
format = '[ $symbol$context ]($style)'

[gcloud]
symbol = "󱇶 "
style = "fg:crust bg:sapphire"

[guix_shell]
symbol = " "
style = "fg:crust bg:sapphire"

[kubernetes]
symbol = "󱃾 "
style = "fg:crust bg:sapphire"

[nats]
symbol = " "
style = "fg:crust bg:sapphire"

[netns]
symbol = "󰛳 "
style = "fg:crust bg:sapphire"

[nix_shell]
symbol = " "
style = "fg:crust bg:sapphire"

[openstack]
symbol = " "
style = "fg:crust bg:sapphire"

[pulumi]
symbol = " "
style = "fg:crust bg:sapphire"

[singularity]
symbol = " "
style = "fg:crust bg:sapphire"

[vagrant]
symbol = " "
style = "fg:crust bg:sapphire"

[battery]
disabled = true
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 100
style = "fg:crust bg:lavender"

[memory_usage]
symbol = "󰍛 "
style = "fg:crust bg:lavender"

[shlvl]
symbol = "󰹍 "
style = "fg:crust bg:lavender"

[status]
symbol = " "
style = "fg:crust bg:lavender"

[sudo]
symbol = " "
style = "fg:crust bg:lavender"

[time]
disabled = true
time_format = "%R"
style = "fg:crust bg:lavender"
format = '[  $time ]($style)'

[cmd_duration]
show_milliseconds = false
format = "[  $duration ]($style)"
style = "fg:crust bg:lavender"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
