{
  inputs,
  ...
}:
{
  imports = [
    ./ssh.nix
    ./zen.nix
    ./foot.nix
    ./noctalia.nix
    ./niri
    ./fcitx5.nix
    ./zeditor.nix
    ./trippy.nix
    ./numbat.nix
    ./mpv.nix
    ./packages.nix
    ./nix-index.nix
    ./email.nix
    ./bat.nix
    ./bottom.nix
    ./btop.nix
    ./direnv.nix
    ./eza.nix
    ./git.nix
    ./gtk.nix
    ./nvf.nix
    #./obs-studio.nix
    ./qt.nix
    ./stylix.nix
    ./tealdeer.nix
    ./xdg.nix
    ./yazi
    ./zoxide.nix
    ./zsh
    inputs.nix-index-database.homeModules.nix-index
  ];
}
