{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.steam.proton;

  makeUserSettingsPy =
    settings:
    let
      merged = cfg.settings // settings;
      entries = lib.mapAttrsToList (k: v: ''"${k}": "${toString v}",'') merged;
    in
    ''
      # Generated by NixOS programs.steam.proton module.
      user_settings = {
      ${lib.concatStringsSep "\n" entries}
      }
    '';

  patchProton =
    { package, settings }:
    let
      settingsFile = pkgs.writeText "user_settings.py" (makeUserSettingsPy settings);
    in
    package.overrideAttrs (old: {
      postInstall = (old.postInstall or "") + ''
        for dir in out steamcompattool; do
          if [ -n "''${!dir:-}" ]; then
            find "''${!dir}" -maxdepth 4 \
              \( -name "user_settings.py" -o -name "user_settings.sample.py" \) \
              2>/dev/null | while read -r f; do
              cp ${settingsFile} "$(dirname "$f")/user_settings.py"
            done
          fi
        done
      '';
    });

in
{
  options.programs.steam.proton = {
    enable = lib.mkEnableOption "Proton {file}`user_settings.py` injection for Steam compatibility tools";

    settings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = ''
        Global Proton settings applied to all packages listed in
        {option}`programs.steam.proton.packages`.
        Per-package settings take precedence over these global values.
      '';
      example = lib.literalExpression ''
        {
          PROTON_USE_NTSYNC = "1";
          PROTON_DXVK_LOWLATENCY = "1";
        }
      '';
    };

    packages = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            package = lib.mkOption {
              type = lib.types.package;
              description = ''
                The Proton compatibility tool package to patch with a generated
                {file}`user_settings.py`.
              '';
              example = lib.literalExpression "pkgs.proton-ge-bin";
            };
            settings = lib.mkOption {
              type = lib.types.attrsOf lib.types.str;
              default = { };
              description = ''
                Per-package settings merged with and overriding
                {option}`programs.steam.proton.settings`.
              '';
              example = lib.literalExpression ''
                {
                  PROTON_LOG = "1";
                }
              '';
            };
          };
        }
      );
      default = [ ];
      description = ''
        List of Proton packages to patch with a generated
        {file}`user_settings.py`. The patched packages are automatically
        added to {option}`programs.steam.extraCompatPackages`.
      '';
      example = lib.literalExpression ''
        [
          { package = pkgs.proton-ge-bin; settings = {}; }
          {
            package = pkgs.dwproton-bin;
            settings.PROTON_USE_WINED3D = "1";
          }
        ]
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.programs.steam.enable;
        message = ''
          `programs.steam.proton` requires `programs.steam.enable = true`.
        '';
      }
    ];

    programs.steam.extraCompatPackages = map patchProton cfg.packages;
  };
}
