{
  imports = [
    ./i686.nix
    ./nix-ld.nix
    ./boot.nix
    ./fonts.nix
    ./sddm.nix
    ./hardware.nix
    ./network
    ./nh.nix
    ./packages.nix
    ./printing.nix
    ./security.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./nix.nix
    ./locale.nix
    ./documentation.nix
    ./system.nix
    ./user.nix
    ./virtualisation.nix
    ./shell.nix
    ./pipewire.nix
    ./power.nix
    ./qbittorrent.nix
    ./storage.nix
    ./performance.nix
    ./peripherals.nix
    #./ollama.nix
    #./location.nix
  ];
}
