{ inputs, ... }:
{
  imports = [
    #./location.nix
    #./ollama.nix
    ./i686.nix
    ./patches.nix
    ./recorder.nix
    ./nix-ld.nix
    ./boot.nix
    ./fcitx5.nix
    ./flatpak.nix
    ./fonts.nix
    ./sddm.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./packages.nix
    ./printing.nix
    ./security.nix
    ./services.nix
    ./starfish.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
    #inputs.nur.modules.nixos.default
    #inputs.lix-module.nixosModules.default
    inputs.disko.nixosModules.disko
  ];
}
